export { default as RelationManager } from './RelationManager.vue'
export { default as RelationManagers } from './RelationManagers.vue'
export type { RelationManagerResource } from './types'
export { default as ResourceTabs } from './ResourceTabs.vue'
export type { ResourceTab, ResourceTabsResource } from './types'
export { default as ResourceBreadcrumbs } from './ResourceBreadcrumbs.vue'
export type { ResourceBreadcrumb } from './types'
export { default as ResourceSubNavigation } from './ResourceSubNavigation.vue'
export type { ResourcePageAction, ResourcePageActionExecutor, ResourcePageWidgetProps, ResourceSubNavigationItem } from './types'
export { default as ResourcePageHeading } from './ResourcePageHeading.vue'
export { default as ResourcePage } from './ResourcePage.vue'
